environment:
  matrix:
    - job_name: win
      appveyor_build_worker_image: Visual Studio 2019

    - job_name: linux
      appveyor_build_worker_image: Ubuntu2004

    - job_name: mac
      appveyor_build_worker_image: macos-catalina

matrix:
  fast_finish: true

version: build-{build}

configuration: Release

platform: x64

clone_depth: 1

init:
  - ps: >-
      $env:DATE = $(Get-Date -Format d-MMM-yyyy)

      $githash = $env:APPVEYOR_REPO_COMMIT.Substring(0, 7)

      $gittag = if ($env:APPVEYOR_REPO_TAG -eq $True) {"_$($env:APPVEYOR_REPO_TAG_NAME)"} else {""}

      Update-AppveyorBuild -Version "$($env:DATE)_g${githash}${gittag}"

      $env:RELEASE_VERSION = $(Get-Date -Format d-MMMM-yyyy)

for:
  -
    matrix:
      only:
        - job_name: win

    build_script:
      - cmake -Wno-dev -B build
      - cmake --build build --config %configuration%

    after_build:
      - 7z a niimath_win.zip .\build\bin\* >$null
      - appveyor PushArtifact niimath_win.zip

  -
    matrix:
      only:
        - job_name: linux

    build_script:
      - export CC=gcc-8 CXX=g++-8
      - cmake -Wno-dev -B build
      - cmake --build build

    after_build:
      - 7z a niimath_lnx.zip ./build/bin/* &>/dev/null
      - appveyor PushArtifact niimath_lnx.zip

  -
    matrix:
      only:
        - job_name: mac

    build_script:
      - sudo xcode-select -s /Applications/Xcode-12.3.app
      - cmake -Wno-dev -DCMAKE_OSX_ARCHITECTURES=x86_64 -B build/x86_64
      - cmake --build build/x86_64
      - cmake -Wno-dev -DCMAKE_OSX_ARCHITECTURES=arm64 -B build/arm64
      - cmake --build build/arm64

    after_build:
      - lipo -create -output build/niimath build/x86_64/bin/niimath build/arm64/bin/niimath
      - zip -j niimath_macos.zip ./build/niimath &>/dev/null
      - appveyor PushArtifact niimath_macos.zip

deploy:
  - provider: GitHub
    tag: $(APPVEYOR_REPO_TAG_NAME)
    release: version $(RELEASE_VERSION) ($(APPVEYOR_REPO_TAG_NAME))
    description: ""
    auth_token:
      secure: 90KUxJbQyRfqQ6N6EOMy4ZVqSt8/bdEpenZBIFSRCyagmvQlGfyN0yKKkeknmtPg
    artifact: /niimath_.*\.zip/
    draft: false
    prerelease: false
    on:
      APPVEYOR_REPO_TAG: true
